language: android
android:
  components:
  - build-tools-28
  - android-28
  - extra

jdk:
  - oraclejdk8
  - openjdk8

install:
- "./gradlew assemble"
script:
- "./gradlew test -i"
after_success:
- bash <(curl -s https://codecov.io/bash)