language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra

jdk:
  - oraclejdk8
  - openjdk8

before_install:
  - yes | sdkmanager "platforms;android-28"
install:
  - "./gradlew assemble"
script:
  - "./gradlew test jacocoTestReport"
after_success:
  - bash <(curl -s https://codecov.io/bash)